use_default_settings: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "de"
  formats:
    - html
    - json

server:
  secret_key: "fakeguard-searxng-secret-change-me"
  limiter: false
  image_proxy: false
  port: 8080
  bind_address: "0.0.0.0"

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: bing
    engine: bing
    shortcut: b
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
